//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { CalendarWeekPlanViewModel } from './CalendarWeekPlanViewModel';

export class CalendarPlanViewModel
{
	public id: number;
	public calendarWeekPlans: CalendarWeekPlanViewModel[] = [];
}
