//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export class CalendarWeekPlanViewModel
{
	public id: number;
	public calendarPlanId: number;
	public startDate: any;
	public endDate: any;
	public nameOfTheWork: string;
	public structuralDivision: string;
	public order: number;
}
