//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { IInstituteEntity } from '../interfaces/IInstituteEntity';
import { GroupViewModel } from './GroupViewModel';

export class DirectionViewModel implements IInstituteEntity
{
	public id: number;
	public name: string;
	public cafedraId: number;
	public groups: GroupViewModel[] = [];
}
