//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { CafedraViewModel } from './CafedraViewModel';

export class InstituteViewModel
{
	public id: number;
	public name: string;
	public cafedras: CafedraViewModel[] = [];
}
