//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { InstituteViewModel } from './InstituteViewModel';
import { CafedraViewModel } from './CafedraViewModel';
import { DirectionViewModel } from './DirectionViewModel';
import { GroupViewModel } from './GroupViewModel';
import { DegreeViewModel } from './DegreeViewModel';
import { CourseViewModel } from './CourseViewModel';

export class InstituteDataViewModel
{
	public institutes: InstituteViewModel[] = [];
	public cafedras: CafedraViewModel[] = [];
	public directions: DirectionViewModel[] = [];
	public groups: GroupViewModel[] = [];
	public degrees: DegreeViewModel[] = [];
	public courses: CourseViewModel[] = [];
}
