//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { UserViewModel } from './UserViewModel';
import { OrganizationViewModel } from './OrganizationViewModel';
import { StaffViewModel } from './StaffViewModel';

export class PracticeViewModel
{
	public id: number;
	public student: UserViewModel;
	public organization: OrganizationViewModel;
	public reportingForm: string;
	public contractNumber: string;
	public responsibleForStudent: StaffViewModel;
	public signsTheContract: StaffViewModel;
}
