//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { UserViewModel } from './UserViewModel';
import { OrganizationViewModel } from './OrganizationViewModel';
import { ReportingForm } from '../enums/ReportingForm';
import { StaffViewModel } from './StaffViewModel';
import { PracticeType } from '../enums/PracticeType';
import { CalendarPlanViewModel } from './CalendarPlanViewModel';

export class PracticeViewModel
{
	public id: number;
	public student: UserViewModel;
	public organization: OrganizationViewModel;
	public reportingForm: ReportingForm;
	public contractNumber: string;
	public responsibleForStudent: StaffViewModel;
	public signsTheContract: StaffViewModel;
	public practiceType: PracticeType;
	public startDate: any;
	public endDate: any;
	public structuralDivision: string;
	public orderOfPassingPractice: string;
	public calendarPlan: CalendarPlanViewModel;
}
