//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export class StudentViewModel
{
	public id: number;
	public firstName: string;
	public secondName: string;
	public lastName: string;
	public email: string;
}
