//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { NotificationViewModel } from './NotificationViewModel';
import { UserViewModel } from './UserViewModel';

export class UserNotificationViewModel
{
	public id: number;
	public notification: NotificationViewModel;
	public userFor: UserViewModel;
	public watched: boolean;
}
