//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { UserRole } from '../enums/UserRole';

export class UserViewModel
{
	public id: number;
	public firstName: string;
	public secondName: string;
	public lastName: string;
	public fio: string;
	public email: string;
	public phone: string;
	public token: string;
	public role: UserRole;
}
