//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export enum InstituteEntity { 
	Institute = 0, 
	Cafedra = 1, 
	Direction = 2, 
	Degree = 3, 
	Group = 4, 
	Course = 5
}
