//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { DirectionReadModel } from './DirectionReadModel';

export class CafedraReadModel
{
	public id: number;
	public instituteId: number;
	public name: string;
	public directions: DirectionReadModel[];
}
