//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { CalendarWeekPlanReadModel } from './CalendarWeekPlanReadModel';

export class CalendarPlanReadModel
{
	public id: number;
	public practiceDetailsId: number;
	public calendarWeelPlans: CalendarWeekPlanReadModel[];
}
