//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export class DiaryReadModel
{
	public id: number;
	public studentId: number;
	public path: string;
	public generated: boolean;
	public send: boolean;
	public sendDate: any;
	public generatedDate: any;
	public perceivedDate: any;
	public completion: number;
	public comment: string;
}
