//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { GroupReadModel } from './GroupReadModel';

export class DirectionReadModel
{
	public id: number;
	public cafedraId: number;
	public name: string;
	public groups: GroupReadModel[];
}
