//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { NotificationType } from '../enums/NotificationType';

export class NotificationReadModel
{
	public id: number;
	public message: string;
	public date: any;
	public type: NotificationType;
}
