//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { OrganizationReadModel } from './OrganizationReadModel';
import { ReportingForm } from '../enums/ReportingForm';
import { StaffReadModel } from './StaffReadModel';
import { PracticeType } from '../enums/PracticeType';
import { CalendarPlanReadModel } from './CalendarPlanReadModel';
import { StudentCharacteristicReadModel } from './StudentCharacteristicReadModel';
import { StudentTaskReadModel } from './StudentTaskReadModel';

export class PracticeReadModel
{
	public id: number;
	public studentId: number;
	public organization: OrganizationReadModel;
	public reportingForm: ReportingForm;
	public contractNumber: string;
	public responsibleForStudent: StaffReadModel;
	public signsTheContract: StaffReadModel;
	public practiceType: PracticeType;
	public startDate: any;
	public endDate: any;
	public structuralDivision: string;
	public orderOfPassingPractice: string;
	public calendarPlan: CalendarPlanReadModel;
	public studentCharacteristic: StudentCharacteristicReadModel;
	public studentTask: StudentTaskReadModel;
}
