//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { UserReadModel } from './UserReadModel';
import { OrganizationReadModel } from './OrganizationReadModel';
import { StaffReadModel } from './StaffReadModel';

export class PracticeReadModel
{
	public id: number;
	public student: UserReadModel;
	public organization: OrganizationReadModel;
	public reportingForm: string;
	public contractNumber: string;
	public responsibleForStudent: StaffReadModel;
	public signsTheContract: StaffReadModel;
}
