//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export class StaffReadModel
{
	public id: number;
	public organizationId: number;
	public fullName: string;
	public job: string;
	public email: string;
	public phone: string;
}
