//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export class StudentsQueryReadModel
{
	public instituteId: number;
	public cafedraId: number;
	public directionId: number;
	public groupId: number;
	public courseId: number;
	public degreeId: number;
}
