//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export class StudentCharacteristicReadModel
{
	public id: number;
	public studentId: number;
	public descriptionByHead: string;
	public descriptionByCafedraHead: string;
	public missedDaysWithReason: number;
	public missedDaysWithoutReason: number;
}
