//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { AnswerType } from '../enums/AnswerType';

export class UserNotificationReadModel
{
	public id: number;
	public notificationId: number;
	public userFor: number;
	public watched: boolean;
	public answer: AnswerType;
}
